### ISSUE TITLE
Ideas-on-map widget disables first click on desktop when 'startWithListOpenOnMobile' is set to true

### ISSUE THREAD

**Issue by rudivanhierden** [Amsterdam/openstad-components#4]
**Description**
When opening the ideas-on-map widget with the 'startWithListOpenOnMobile' set to true, the first click on Desktop does nothing. After the first click everything works like normal.

**Suggested fix**
Only listen to the 'startWithListOpenOnMobile' value when being viewed on mobile.

Related ticket: https://trello.com/c/9nhrQOVj/91-eerste-click-doet-niks-wanneer-op-mobiel-de-lijst-standaard-open-staat

**Comment by nlsvgtr** [comment]
This has been fixed but this ticket has not been updated
